name: Lint+Test+Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: Run static analysis tests
        shell: bash
        run: scripts/lint.sh

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: build_test
        shell: bash
        run: .github/workflows/build_and_test.sh

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: Run e2e tests
        shell: bash
        run: scripts/run.sh
        env:
          E2E: true
  
  load-test:
    name: Load Test
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: Run load tests
        shell: bash
        run: scripts/tests.load.sh
        env:
          TERMINAL_HEIGHT: 1000 # Set the terminal height for the load test to reach before terminating.
